language: go
go:
  - stable

sudo: false

before_install:
  - nvm install stable
  - nvm use stable
  - export CHROME_BIN=chromium-browser  # Karma CI
  - export DISPLAY=:99.0

#install:
# - npm install
# -

before_script:
  - sh -e /etc/init.d/xvfb start
  # - nohup bash -c webdriver-manager start 2>&1 &  # Protractor CI
  - sleep 1  # give server time to start

# npm test

after_failure:
  - cat /home/travis/build/mgechev/angular2-seed/npm-debug.log

branches:
  only: master

notifications:
  email: true

env:
  global:
    # https://github.com/DefinitelyTyped/tsd#tsdrc
    # Token has no scope (read-only access to public information)
    - TSD_GITHUB_TOKEN=19937e314622fdaf0f26aa9b6738de2642b7a6f9

cache:
  directories: node_modules
