language: go
go:
  - 1.6

sudo: false

before_install:
  - nvm install stable
  - nvm use stable
  - export CHROME_BIN=chromium-browser  # Karma CI
  - export DISPLAY=:99.0

install:
 - npm install
 - go get -t -v ./...

before_script:
  - sh -e /etc/init.d/xvfb start
  - npm run webdriver-update
  - nohup npm run webdriver-start 2>&1 &
  #- sleep 1  # give server time to start

script:
  - go test -v -cover ./src/backend/omni-tempore-backend/...
  - npm test
  - npm run build.prod
  - go install ./...
  ## start backend
  - nohup npm start.backend 2>&1 &
  - nohup npm serve.e2e 2>&1 &
  - sleep 3 # give server time to start
  - npm run e2e


after_failure:
  - cat /home/travis/build/mgechev/angular2-seed/npm-debug.log

notifications:
  email: true

env:
  global:
    # https://github.com/DefinitelyTyped/tsd#tsdrc
    # Token has no scope (read-only access to public information)
    - TSD_GITHUB_TOKEN=19937e314622fdaf0f26aa9b6738de2642b7a6f9

cache:
  directories: node_modules
