language: go
go:
- 1.6
sudo: false
addons:
  sauce_connect: true
before_install:
- nvm install stable
- nvm use stable
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install
- go get -t -v ./...
before_script:
- sh -e /etc/init.d/xvfb start
- npm run webdriver-update
- nohup npm run webdriver-start > webdriver-start.out 2>&1 &
script:
- go test -v -cover ./src/backend/omni-tempore-backend/...
- npm test
- npm run build.prod
- go install ./...
- nohup npm run serve.e2e > serve.e2e.out 2>&1 &
- nohup npm run start.backend > start.backend.out 2>&1 &
- sleep 15
- npm run e2e
after_failure:
- cat serve.e2e.out
- cat start.backend.out
- cat webdriver-start.out
- cat npm-debug.log
notifications:
  email: true
env:
  global:
  - secure: x2VzCmW81rArwZL7C7OTkqEuRP+ispYcOtI9eBCV0A0kRp1DPn9TpB5EzxOdXjCmyFojdH4DBDanOrNRXG2BT+IBfZSkORo7Twj0RbG17NCoxGm2iYg58KKAqdo192f8Sswn1bvHAa0VTNUgXTDN6bQjnMx/lkjNlQiNjPGu7nVXhUnw9euV+OcMxrN04br5UYglCj85xAyO6WqYHBJlhL7qIdeVLL7FgoK7+4lFrqfdgECPQZAUTA6QU+q9n0niBumaGzBGPkQXtrqgS+kUrcidMPP8XzYqPWb04r+awYVC1463PVFZu+ecsF5MfUw3ing3fySpgtGHBm/Mdh24OSpGWO7iq2DqXnZpzYUytPrYxWV78HEru78Mt3eS7yudH1KlkUSPuPs7aFNsQ6idvMfPYLnzKARSZpMChB4bShy8s3Cjl03tpR3kb3R14kg5ylzRcawFwGG23v6pUiItYZyZ5EmY+GpK9NtSr8a08gghhswHqeE/SkbDfjZGiLcACznx4O3Bx9olGxt9knPqe0bLV5UXHZ3mIEnKsTKPQWABlBuD0QiS7c39lZ2UutQPBoXfPIlCxgm7uuEy+I7ogfyJ16rQASZ1ePBC0MDJWEbi/RYkx3JAK2v0Mr4sdARv8WXZ+MmoSrnDwsOEA72q8+LVZH8j5IuJ6wqLOiFTOgo=
  - secure: TOsUyQjucgtG+/4jojKqWoG0XIaxKQOld0NlEXugJZep6QVPocd5djDZn3K+acYNfCq8oY/ebyp8khgmuzsXXw6fibDG/iEtgZxLKuiyPhlT5dIUojirGVaNOcFByvaXtS17e4VryTPE8bi0Yoq0cJDixPofIUcWqALC84M9V8quFhM3xDwy+ljOU5bexWfL8s8wd5HlFwD/fnM7LERB7EhCOd3wZQKfDeKVTCOFWD+18Z2MbXLrCNmRtQFP1VnvN9O7CQitJVvs9ReH8IrFyrIOZtp1QHa08Q81AD0jdLnLQDzpPNS5uUZ/eA2VP89GKL2zQqr6rfOi5nMTDUKTRLhvcHqZkaoNxr0MwTyYL5V8CmGemFNC8+9CjXj3mP5ycPKkmn0AzcHOLb2QCboVoEvfSi86EcpBE0I9BiLbDYKiTOUrFHrQF/F21jmN62RXYi5ugn2HcVw/R/8BwEBJ72eWc1bR6pxRvrV8Uo+16HVC09vhZgHe9Z15ocI4K/HjHGvY8+8SqJhBhjOsfla8NFlXOnV1CqFoaVYmzJG/oOjt+Su6kCZGVRe7LJ2VkO5QtvFN708nuMI/neLLlkHHwOr3x7MAUsttnKsnJ3uxjXRrmqCkcYi6CiqLXpwoSStwFrRv1YWCgm2cfBLY9HgwLvqItKhmxxJmNxlSk5zK1kQ=
  - secure: kAvhXGZQ5taEMIjJE3Ey7fj25K8afPGGn35pMHJ5mr+nGt2zRuubYaFDHkOFHJqmb4QRB1DFCuo8LqA6GhkPheq3IjW47XWYt7O5eB/SC4uzX3VICvh7SqVPGRIffl/lRaiNIGdnOxteKtxbangGeRA8iqS/+6iB0FcLP3Pilao0AzJgllr19f4CReG+/pED9TEbBpXxsg0vAm09Re/CJy8GwK5RVfv5a+SQbXplXqADif7Lsr4YvdED+FbfIulPe1+4j6Q/HEf9QGuLpuEIbR+BShAyLaabvCr1qJmRZodJVfNXoIr5knJvWjVWlV1nhtlLO8h2l4sV3VRjywjP7d/pS5nZI1ajvhDrfr2t4oqeiHNO4DWyG/OSf1CghWEWrruDVrGxuT1Oa3kXA3rfmH6hWxCKh6qCM1LFV1UrQnH1Of74BFcC+YHUraL3wkNxydwk35Z6TB0BIcP/tqgaZL0AFr6dSi+kD67qWEGhDpsfPyx7to9XQGWZI7soUnldTjgrWSQmQvzk0aexLmeCOVqCGo2+M4vL2I9cTE0b6t3/V/DZurgjLn6/bPTIY4T6PoY96WIZl6a9Cev2520f0ogSLyz5m7RposdzcjON3UvYW0f55KCqde393CKHS6DNkbsm1iYBf73Tm492ou9J35ly2AAVRFrKsy8rkkak/aM=
cache:
  directories: node_modules
